version: '3.5'

services:
  postgres:
    container_name: pg
    image: postgres
    env_file:
      - path: ./.env
        required: true
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
